CREATE DATABASE db_marketplace;

CREATE TABLE customers (
	customer_id 	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_code 	VARCHAR(20) UNIQUE NOT NULL,
	full_name 		VARCHAR(100) NOT NULL,
	email 			VARCHAR(120) UNIQUE NOT NULL,
	phone 			VARCHAR(15),
	registered_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE addresses (
	address_id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_id 	INTEGER NOT NULL REFERENCES customers(customer_id) ON UPDATE CASCADE,
	address_label 	VARCHAR(30) NOT NULL DEFAULT 'Rumah',
	recipient_name 	VARCHAR(100) NOT NULL,
	recipient_phone VARCHAR(15) NOT NULL,
	address_line 	VARCHAR(200) NOT NULL,
	village 		VARCHAR(100),
	district 		VARCHAR(100),
	city 			VARCHAR(60) NOT NULL,
	regency 		VARCHAR(100),
	province 		VARCHAR(60) NOT NULL DEFAULT 'Kalimantan Barat',
	postal_code 	VARCHAR(10),
	is_primary 		BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE categories (
	category_id 	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category_name 	VARCHAR(30) UNIQUE NOT NULL,
	description 	TEXT
);

CREATE TABLE products (
	product_id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_code 	VARCHAR(20) UNIQUE NOT NULL,
	product_name 	VARCHAR(150) NOT NULL,
	category_id 	INTEGER NOT NULL REFERENCES categories(category_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	price 			NUMERIC(14,2) NOT NULL CHECK (price >= 0),
	stock 			INTEGER NOT NULL CHECK (stock >= 0),
	weight_gram 	INTEGER CHECK (weight_gram > 0),
	is_active 		BOOLEAN NOT NULL DEFAULT TRUE,
	created_at 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
	order_id 			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_code 			VARCHAR(30) UNIQUE NOT NULL,
	customer_id 		INTEGER NOT NULL REFERENCES customers(customer_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	shipping_address_id INTEGER NOT NULL REFERENCES addresses(address_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	order_date 			TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status 				VARCHAR(20) NOT NULL CHECK (status IN ('pending','paid','shipped','completed','cancelled')),
	shipping_cost 		NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (shipping_cost >= 0)
);

CREATE TABLE order_items (
	order_item_id 	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id 		INTEGER NOT NULL REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE CASCADE,
	product_id 		INTEGER NOT NULL REFERENCES products(product_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	quantity 		INTEGER NOT NULL CHECK (quantity > 0),
	unit_price 		NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
	discount 		NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (discount >= 0 AND discount <= 100),
	CONSTRAINT uq_order_product UNIQUE (order_id, product_id)
);

CREATE TABLE payments (
	payment_id 			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id 			INTEGER UNIQUE NOT NULL REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	payment_method 		VARCHAR(30) NOT NULL CHECK (payment_method IN ('QRIS','Transfer Bank','E-Wallet','Virtual Account','COD')),
	payment_date 		TIMESTAMP,
	amount 				NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
	payment_status 		VARCHAR(20) NOT NULL CHECK (payment_status IN ('pending','paid','failed','refunded')),
	reference_number 	VARCHAR(50) UNIQUE
);

INSERT INTO customers (customer_id, customer_code, full_name, email, phone, registered_at) VALUES
(1, 'CUS001', 'Andi Saputra', 'andi.saputra01@example.com', '081256710001', '2026-06-02 09:15:00'),
(2, 'CUS002', 'Siti Rahmawati', 'siti.rahmawati02@example.com', '082156710002', '2026-06-05 10:20:00'),
(3, 'CUS003', 'Budi Santoso', 'budi.santoso03@example.com', '085256710003', '2026-06-09 13:10:00'),
(4, 'CUS004', 'Dewi Lestari', 'dewi.lestari04@example.com', '081356710004', '2026-06-12 08:45:00'),
(5, 'CUS005', 'Fajar Hidayat', 'fajar.hidayat05@example.com', '082256710005', '2026-06-16 11:30:00'),
(6, 'CUS006', 'Rina Kurnia', 'rina.kurnia06@example.com', '085356710006', '2026-06-20 14:05:00'),
(7, 'CUS007', 'Taufik Pratama', 'taufik.pratama07@example.com', '081256710007', '2026-06-23 09:55:00'),
(8, 'CUS008', 'Maya Anggraini', 'maya.anggraini08@example.com', '082156710008', '2026-06-27 15:20:00'),
(9, 'CUS009', 'Rian Setiawan', 'rian.setiawan09@example.com', '085256710009', '2026-07-01 08:30:00'),
(10, 'CUS010', 'Putri Amelia', 'putri.amelia10@example.com', '081356710010', '2026-07-05 10:40:00'),
(11, 'CUS011', 'Ilham Ramadhan', 'ilham.ramadhan11@example.com', '082256710011', '2026-07-09 12:15:00'),
(12, 'CUS012', 'Nisa Maulida', 'nisa.maulida12@example.com', '085356710012', '2026-07-13 09:25:00'),
(13, 'CUS013', 'Bayu Nugroho', 'bayu.nugroho13@example.com', '081256710013', '2026-07-17 16:10:00'),
(14, 'CUS014', 'Ayu Permata', 'ayu.permata14@example.com', '082156710014', '2026-07-21 11:05:00'),
(15, 'CUS015', 'Dimas Firmansyah', 'dimas.firmansyah15@example.com', '085256710015', '2026-07-25 13:35:00');

INSERT INTO addresses (address_id, customer_id, address_label, recipient_name, recipient_phone, address_line, village, district, city, regency, province, postal_code, is_primary) VALUES
(1, 1, 'Rumah', 'Andi Saputra', '081256710001', 'Jl. Gajah Mada No. 21', 'Benua Melayu Darat', 'Pontianak Selatan', 'Pontianak', 'Kota Pontianak', 'Kalimantan Barat', 78121, TRUE),
(2, 2, 'Rumah', 'Siti Rahmawati', '082156710002', 'Jl. Alianyang No. 18', 'Pasiran', 'Singkawang Barat', 'Singkawang', 'Kota Singkawang', 'Kalimantan Barat', 79123, TRUE),
(3, 3, 'Rumah', 'Budi Santoso', '085256710003', 'Jl. Adisucipto No. 35', 'Sungai Raya', 'Sungai Raya', 'Sungai Raya', 'Kabupaten Kubu Raya', 'Kalimantan Barat', 78391, TRUE),
(4, 4, 'Rumah', 'Dewi Lestari', '081356710004', 'Jl. Daeng Manambon No. 12', 'Terusan', 'Mempawah Hilir', 'Mempawah', 'Kabupaten Mempawah', 'Kalimantan Barat', 78912, TRUE),
(5, 5, 'Rumah', 'Fajar Hidayat', '082256710005', 'Jl. Pendidikan No. 9', 'Dalam Kaum', 'Sambas', 'Sambas', 'Kabupaten Sambas', 'Kalimantan Barat', 79462, TRUE),
(6, 6, 'Rumah', 'Rina Kurnia', '085356710006', 'Jl. Sanggau Ledo No. 14', 'Bumi Emas', 'Bengkayang', 'Bengkayang', 'Kabupaten Bengkayang', 'Kalimantan Barat', 79211, TRUE),
(7, 7, 'Rumah', 'Taufik Pratama', '081256710007', 'Jl. Pemuda No. 27', 'Hilir Kantor', 'Ngabang', 'Ngabang', 'Kabupaten Landak', 'Kalimantan Barat', 79357, TRUE),
(8, 8, 'Rumah', 'Maya Anggraini', '082156710008', 'Jl. Jenderal Sudirman No. 31', 'Beringin', 'Kapuas', 'Sanggau', 'Kabupaten Sanggau', 'Kalimantan Barat', 78512, TRUE),
(9, 9, 'Rumah', 'Rian Setiawan', '085256710009', 'Jl. Merdeka Timur No. 16', 'Sungai Ringin', 'Sekadau Hilir', 'Sekadau', 'Kabupaten Sekadau', 'Kalimantan Barat', 79582, TRUE),
(10, 10, 'Rumah', 'Putri Amelia', '081356710010', 'Jl. Lintas Melawi No. 44', 'Ladang', 'Sintang', 'Sintang', 'Kabupaten Sintang', 'Kalimantan Barat', 78614, TRUE),
(11, 11, 'Rumah', 'Ilham Ramadhan', '082256710011', 'Jl. Juang No. 10', 'Tanjung Niaga', 'Nanga Pinoh', 'Nanga Pinoh', 'Kabupaten Melawi', 'Kalimantan Barat', 79672, TRUE),
(12, 12, 'Rumah', 'Nisa Maulida', '085356710012', 'Jl. Kom Yos Sudarso No. 8', 'Putussibau Kota', 'Putussibau Utara', 'Putussibau', 'Kabupaten Kapuas Hulu', 'Kalimantan Barat', 78711, TRUE),
(13, 13, 'Rumah', 'Bayu Nugroho', '081256710013', 'Jl. R. Suprapto No. 23', 'Kantor', 'Delta Pawan', 'Ketapang', 'Kabupaten Ketapang', 'Kalimantan Barat', 78813, TRUE),
(14, 14, 'Rumah', 'Ayu Permata', '082156710014', 'Jl. Tanjung Pura No. 11', 'Sutera', 'Sukadana', 'Sukadana', 'Kabupaten Kayong Utara', 'Kalimantan Barat', 78852, TRUE),
(15, 15, 'Rumah', 'Dimas Firmansyah', '085256710015', 'Jl. Danau Sentarum No. 52', 'Sungai Bangkong', 'Pontianak Kota', 'Pontianak', 'Kota Pontianak', 'Kalimantan Barat', 78116, TRUE);

INSERT INTO categories (category_id, category_name, description) VALUES
(1, 'Sembako & Makanan', 'Bahan makanan, minuman, dan kebutuhan dapur sehari-hari'),
(2, 'Handphone & Aksesori', 'Perangkat handphone dan aksesori pendukung'),
(3, 'Komputer & Aksesori', 'Perangkat dan aksesori komputer'),
(4, 'Elektronik Rumah', 'Peralatan elektronik untuk kebutuhan rumah'),
(5, 'Rumah Tangga', 'Peralatan dan perlengkapan rumah tangga'),
(6, 'Perawatan Diri', 'Produk kebersihan dan perawatan tubuh'),
(7, 'Fashion', 'Pakaian dan tas untuk penggunaan sehari-hari');

INSERT INTO products (product_id, product_code, product_name, category_id, price, stock, weight_gram, is_active, created_at) VALUES
(1, 'PRD001', 'Beras Premium 5 kg', 1, 82000, 80, 5000, TRUE, '2026-05-01 09:00:00'),
(2, 'PRD002', 'Minyak Goreng 2 Liter', 1, 39500, 120, 2000, TRUE, '2026-05-02 09:00:00'),
(3, 'PRD003', 'Gula Pasir 1 kg', 1, 18500, 150, 1000, TRUE, '2026-05-03 09:00:00'),
(4, 'PRD004', 'Susu UHT Full Cream 1 Liter', 1, 21500, 100, 1000, TRUE, '2026-05-04 09:00:00'),
(5, 'PRD005', 'Kopi Bubuk 200 gram', 1, 28000, 90, 200, TRUE, '2026-05-05 09:00:00'),
(6, 'PRD006', 'Mi Instan Goreng 1 Dus isi 40', 1, 122000, 70, 3200, TRUE, '2026-05-06 09:00:00'),
(7, 'PRD007', 'Air Mineral 600 ml Dus isi 24', 1, 55000, 85, 14500, TRUE, '2026-05-07 09:00:00'),
(8, 'PRD008', 'Tepung Terigu 1 kg', 1, 15000, 130, 1000, TRUE, '2026-05-08 09:00:00'),
(9, 'PRD009', 'Telur Ayam Ras 1 Tray isi 30', 1, 57000, 60, 1900, TRUE, '2026-05-09 09:00:00'),
(10, 'PRD010', 'Biskuit Kaleng 600 gram', 1, 75000, 55, 750, TRUE, '2026-05-10 09:00:00'),
(11, 'PRD011', 'Charger USB-C 20W', 2, 125000, 95, 120, TRUE, '2026-05-11 09:00:00'),
(12, 'PRD012', 'Power Bank 10000 mAh', 2, 199000, 80, 250, TRUE, '2026-05-12 09:00:00'),
(13, 'PRD013', 'TWS Bluetooth', 2, 225000, 75, 120, TRUE, '2026-05-13 09:00:00'),
(14, 'PRD014', 'Kabel Data USB-C 1 Meter', 2, 55000, 140, 80, TRUE, '2026-05-14 09:00:00'),
(15, 'PRD015', 'Earphone Kabel dengan Mikrofon', 2, 85000, 110, 90, TRUE, '2026-05-15 09:00:00'),
(16, 'PRD016', 'Mouse Wireless', 3, 125000, 100, 100, TRUE, '2026-05-16 09:00:00'),
(17, 'PRD017', 'Keyboard Mechanical Entry Level', 3, 375000, 45, 850, TRUE, '2026-05-17 09:00:00'),
(18, 'PRD018', 'Flashdisk USB 64 GB', 3, 95000, 120, 30, TRUE, '2026-05-18 09:00:00'),
(19, 'PRD019', 'SSD SATA 512 GB', 3, 695000, 50, 80, TRUE, '2026-05-19 09:00:00'),
(20, 'PRD020', 'Router WiFi Dual Band AC1200', 3, 399000, 45, 350, TRUE, '2026-05-20 09:00:00'),
(21, 'PRD021', 'Rice Cooker 1.8 Liter', 4, 475000, 40, 3500, TRUE, '2026-05-21 09:00:00'),
(22, 'PRD022', 'Ketel Listrik 1.5 Liter', 4, 245000, 55, 1100, TRUE, '2026-05-22 09:00:00'),
(23, 'PRD023', 'Lampu LED 12 Watt', 4, 35000, 180, 120, TRUE, '2026-05-23 09:00:00'),
(24, 'PRD024', 'Wajan Anti Lengket 28 cm', 5, 225000, 65, 1200, TRUE, '2026-05-24 09:00:00'),
(25, 'PRD025', 'Kotak Penyimpanan 50 Liter', 5, 165000, 70, 1800, TRUE, '2026-05-25 09:00:00'),
(26, 'PRD026', 'Shampoo 650 ml', 6, 68000, 100, 720, TRUE, '2026-05-26 09:00:00'),
(27, 'PRD027', 'Sabun Mandi Cair 450 ml', 6, 42000, 115, 500, TRUE, '2026-05-27 09:00:00'),
(28, 'PRD028', 'Sunscreen SPF 50 50 ml', 6, 95000, 90, 80, TRUE, '2026-05-28 09:00:00'),
(29, 'PRD029', 'Kaos Katun Basic Unisex', 7, 79000, 85, 250, TRUE, '2026-05-29 09:00:00'),
(30, 'PRD030', 'Tas Ransel Casual 20 Liter', 7, 185000, 60, 650, TRUE, '2026-05-30 09:00:00');

INSERT INTO orders (order_id, order_code, customer_id, shipping_address_id, order_date, status, shipping_cost) VALUES
(1, 'ORD2026001', 1, 1, '2026-08-03 09:20:00', 'completed', 12000),
(2, 'ORD2026002', 2, 2, '2026-08-05 10:05:00', 'shipped', 25000),
(3, 'ORD2026003', 3, 3, '2026-08-07 13:40:00', 'paid', 15000),
(4, 'ORD2026004', 4, 4, '2026-08-09 11:15:00', 'completed', 22000),
(5, 'ORD2026005', 5, 5, '2026-08-11 15:30:00', 'pending', 35000),
(6, 'ORD2026006', 6, 6, '2026-08-13 08:50:00', 'cancelled', 32000),
(7, 'ORD2026007', 7, 7, '2026-08-15 14:25:00', 'completed', 30000),
(8, 'ORD2026008', 8, 8, '2026-08-17 10:45:00', 'shipped', 38000),
(9, 'ORD2026009', 9, 9, '2026-08-19 12:10:00', 'paid', 42000),
(10, 'ORD2026010', 10, 10, '2026-08-21 16:05:00', 'completed', 48000);

INSERT INTO order_items (order_item_id, order_id, product_id, quantity, unit_price, discount) VALUES
(1, 1, 1, 1, 82000, 0.00),
(2, 1, 11, 1, 125000, 5.00),
(3, 1, 26, 2, 68000, 0.00),
(4, 2, 6, 1, 122000, 0.00),
(5, 2, 12, 1, 199000, 10.00),
(6, 2, 29, 2, 79000, 0.00),
(7, 3, 2, 2, 39500, 0.00),
(8, 3, 16, 1, 125000, 5.00),
(9, 3, 23, 4, 35000, 0.00),
(10, 4, 9, 1, 57000, 0.00),
(11, 4, 21, 1, 475000, 10.00),
(12, 4, 27, 2, 42000, 0.00),
(13, 5, 3, 3, 18500, 0.00),
(14, 5, 18, 1, 95000, 0.00),
(15, 5, 25, 1, 165000, 5.00),
(16, 6, 4, 2, 21500, 0.00),
(17, 6, 13, 1, 225000, 10.00),
(18, 6, 30, 1, 185000, 0.00),
(19, 7, 7, 1, 55000, 0.00),
(20, 7, 17, 1, 375000, 5.00),
(21, 7, 28, 1, 95000, 0.00),
(22, 8, 8, 2, 15000, 0.00),
(23, 8, 19, 1, 695000, 10.00),
(24, 8, 24, 1, 225000, 0.00),
(25, 9, 5, 2, 28000, 0.00),
(26, 9, 14, 2, 55000, 5.00),
(27, 9, 22, 1, 245000, 0.00),
(28, 10, 10, 1, 75000, 0.00),
(29, 10, 20, 1, 399000, 10.00),
(30, 10, 15, 2, 85000, 0.00);

INSERT INTO payments (payment_id, order_id, payment_method, payment_date, amount, payment_status, reference_number) VALUES
(1, 1, 'QRIS', '2026-08-03 09:32:00', 348750, 'paid', 'PAY2026001'),
(2, 2, 'Transfer Bank', '2026-08-05 10:18:00', 484100, 'paid', 'PAY2026002'),
(3, 3, 'E-Wallet', '2026-08-07 13:50:00', 352750, 'paid', 'PAY2026003'),
(4, 4, 'Virtual Account', '2026-08-09 11:28:00', 590500, 'paid', 'PAY2026004'),
(5, 5, 'COD', NULL, 342250, 'pending', NULL),
(6, 6, 'QRIS', '2026-08-13 09:05:00', 462500, 'refunded', 'PAY2026006'),
(7, 7, 'Transfer Bank', '2026-08-15 14:37:00', 536250, 'paid', 'PAY2026007'),
(8, 8, 'E-Wallet', '2026-08-17 10:56:00', 918500, 'paid', 'PAY2026008'),
(9, 9, 'Virtual Account', '2026-08-19 12:24:00', 447500, 'paid', 'PAY2026009'),
(10, 10, 'COD', '2026-08-22 12:15:00', 652100, 'paid', 'PAY2026010');

SELECT COUNT(*) AS total_produk,
    SUM(stock) AS total_stock,
    AVG(price) AS rata_rata_harga,
    MAX(price) AS harga_tertinggi,
    MIN(price) AS harga_terendah
FROM products;

SELECT category_id,
    COUNT(*) AS total_produk,
    SUM(stock) AS total_stock,
    AVG(stock) AS rata_rata_stock,
    MAX(stock) AS stock_tertinggi,
    MIN(stock) AS stock_terendah
FROM products
GROUP BY category_id;

SELECT category_id,
    COUNT(*) AS total_produk,
    SUM(stock) AS total_stock,
    AVG(price) AS rata_rata_harga,
    MAX(price) AS harga_tertinggi,
    MIN(price) AS harga_terendah
FROM products
WHERE is_active = true
GROUP BY category_id;

SELECT category_id,
    COUNT(*) AS total_produk,
    SUM(stock) AS total_stock,
    AVG(price) AS rata_rata_harga
FROM products
GROUP BY category_id
HAVING COUNT(*) >= 2;

SELECT category_id,
    COUNT(*) AS total_produk,
    SUM(stock) AS total_stock,
    AVG(stock) AS rata_rata_stock
FROM products
GROUP BY category_id
HAVING SUM(stock) >= 20 AND AVG(stock) > 5;

SELECT orders.order_code,
    orders.order_date,
    customers.full_name,
    addresses.city,
    addresses.province,
    orders.status
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN addresses ON orders.customer_id = addresses.customer_id;

SELECT orders.order_code,
    customers.full_name,
    products.product_name,
    order_items.quantity,
    order_items.unit_price,
    order_items.discount
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN order_items ON orders.order_id = order_items.order_id
JOIN products ON order_items.product_id = products.product_id;

SELECT orders.order_code,
    customers.full_name,
    products.product_name,
    order_items.quantity,
    order_items.unit_price,
    order_items.discount,
    (order_items.quantity * order_items.unit_price) - order_items.discount AS subtotal
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN order_items ON orders.order_id = order_items.order_id
JOIN products ON order_items.product_id = products.product_id;

SELECT orders.order_code,
    customers.full_name,
    addresses.city,
    products.product_name,
    categories.category_name,
    order_items.quantity,
    (order_items.quantity * order_items.unit_price) - order_items.discount AS subtotal,
    payments.payment_method,
    payments.payment_status
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN addresses ON orders.shipping_address_id = addresses.address_id
JOIN order_items ON orders.order_id = order_items.order_id
JOIN products ON order_items.product_id = products.product_id
JOIN categories ON products.category_id = categories.category_id
LEFT JOIN payments ON orders.order_id = payments.order_id;

SELECT orders.order_code,
    customers.full_name,
    addresses.city,
    products.product_name,
    categories.category_name,
    order_items.quantity,
    (order_items.quantity * order_items.unit_price) - order_items.discount AS subtotal,
    payments.payment_method,
    payments.payment_status
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN addresses ON orders.shipping_address_id = addresses.address_id
JOIN order_items ON orders.order_id = order_items.order_id
JOIN products ON order_items.product_id = products.product_id
JOIN categories ON products.category_id = categories.category_id
JOIN payments ON orders.order_id = payments.order_id
WHERE payments.payment_status = 'paid';

SELECT orders.order_code,
    customers.full_name,
    orders.status AS order_status,
    products.product_name,
    categories.category_name,
    (order_items.quantity * order_items.unit_price) - order_items.discount AS subtotal,
    payments.payment_method,
    payments.payment_status
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN order_items ON orders.order_id = order_items.order_id
JOIN products ON order_items.product_id = products.product_id
JOIN categories ON products.category_id = categories.category_id
LEFT JOIN payments ON orders.order_id = payments.order_id;

SELECT orders.order_code,
    customers.full_name,
    orders.status AS order_status,
    products.product_name,
    categories.category_name,
    (order_items.quantity * order_items.unit_price) - order_items.discount AS subtotal,
    payments.payment_method,
    payments.payment_status,
    CASE 
        WHEN (order_items.quantity * order_items.unit_price) - order_items.discount >= 2000000 THEN 'High Value'
        WHEN (order_items.quantity * order_items.unit_price) - order_items.discount >= 1000000 THEN 'Medium Value'
        ELSE 'Regular'
    END AS transaction_level
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN order_items ON orders.order_id = order_items.order_id
JOIN products ON order_items.product_id = products.product_id
JOIN categories ON products.category_id = categories.category_id
LEFT JOIN payments ON orders.order_id = payments.order_id;

SELECT customers.customer_id,
 customers.full_name,
 COUNT(orders.order_id) AS total_order
 FROM customers
 LEFT JOIN orders ON customers.customer_id = orders.customer_id
 GROUP BY customers.customer_id, customers.full_name
 ORDER BY total_order DESC;

SELECT products.product_name,
 SUM(order_items.quantity) AS total_quantity,
 SUM((order_items.quantity * order_items.unit_price) - order_items.discount) AS total_penjualan
 FROM products
 JOIN order_items ON products.product_id = order_items.product_id
 GROUP BY products.product_id, products.product_name
 ORDER BY total_penjualan DESC;

SELECT categories.category_name,
 COUNT(DISTINCT products.product_id) AS total_product_terjual,
 SUM(order_items.quantity) AS total_quantity,
 SUM((order_items.quantity * order_items.unit_price) - order_items.discount) AS total_sales,
 AVG((order_items.quantity * order_items.unit_price) - order_items.discount) AS avg_item_sales,
 MAX((order_items.quantity * order_items.unit_price) - order_items.discount) AS max_item_sales,
 MIN((order_items.quantity * order_items.unit_price) - order_items.discount) AS min_item_sales
 FROM categories
 JOIN products ON categories.category_id = products.category_id
 JOIN order_items ON products.product_id = order_items.product_id
 GROUP BY categories.category_id, categories.category_name;

SELECT orders.order_code,
 customers.full_name,
 COUNT(DISTINCT order_items.product_id) AS total_item,
 SUM(order_items.quantity) AS total_quantity,
 SUM((order_items.quantity * order_items.unit_price) - order_items.discount) AS product_total,
 orders.shipping_cost,
 SUM((order_items.quantity * order_items.unit_price) - order_items.discount) + orders.shipping_cost AS grand_total
 FROM orders
 JOIN customers ON orders.customer_id = customers.customer_id
 JOIN order_items ON orders.order_id = order_items.order_id
 GROUP BY orders.order_id, orders.order_code, customers.full_name, orders.shipping_cost;

SELECT orders.order_code,
 customers.full_name,
COUNT(DISTINCT order_items.product_id) AS total_item,
SUM(order_items.quantity) AS total_quantity,
SUM((order_items.quantity * order_items.unit_price) - order_items.discount) AS product_total,
 orders.shipping_cost,
SUM((order_items.quantity * order_items.unit_price) - order_items.discount) + orders.shipping_cost AS grand_total
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id
JOIN order_items ON orders.order_id = order_items.order_id
 ROUP BY orders.order_id, orders.order_code, customers.full_name, orders.shipping_cost
 HAVING SUM(order_items.quantity) > COUNT(DISTINCT order_items.product_id) 
 AND SUM((order_items.quantity * order_items.unit_price) - order_items.discount) + orders.shipping_cost > 1000000;


